version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app_container
    ports:
      - "8000:8000"
    depends_on:
      - db  # Зависимость от сервиса базы данных
    env_file:
      - .env  # Загружаем переменные окружения
    restart: always  # Автоматический перезапуск контейнера
    command: >
      bash -c "sleep 5 && alembic upgrade head && python app.py"


  db:
    image: postgres:15
    container_name: db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB}  
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранилище данных Postgres
    restart: always  # Автоматический перезапуск контейнера

volumes:
  postgres_data:  # Объявляем volume для базы данных
