"""Initial migration

Revision ID: 1db730d03105
Revises: 
Create Date: 2025-01-03 22:38:08.979479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db730d03105'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_forecast_city'), 'city_forecast', ['city'], unique=False)
    op.create_index(op.f('ix_city_forecast_date_time'), 'city_forecast', ['date_time'], unique=False)
    op.create_index(op.f('ix_city_forecast_id'), 'city_forecast', ['id'], unique=False)
    op.create_table('weather_icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_code', sa.String(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_icons_icon_code'), 'weather_icons', ['icon_code'], unique=True)
    op.create_index(op.f('ix_weather_icons_id'), 'weather_icons', ['id'], unique=False)
    op.create_table('forecast_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_forecast_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('cloudiness', sa.String(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.String(), nullable=True),
    sa.Column('icon_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_forecast_id'], ['city_forecast.id'], ),
    sa.ForeignKeyConstraint(['icon_code'], ['weather_icons.icon_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_details_id'), 'forecast_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_details_id'), table_name='forecast_details')
    op.drop_table('forecast_details')
    op.drop_index(op.f('ix_weather_icons_id'), table_name='weather_icons')
    op.drop_index(op.f('ix_weather_icons_icon_code'), table_name='weather_icons')
    op.drop_table('weather_icons')
    op.drop_index(op.f('ix_city_forecast_id'), table_name='city_forecast')
    op.drop_index(op.f('ix_city_forecast_date_time'), table_name='city_forecast')
    op.drop_index(op.f('ix_city_forecast_city'), table_name='city_forecast')
    op.drop_table('city_forecast')
    # ### end Alembic commands ###
